apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: dXNlcm5hbWU= # base64 encoded value of 'username'
  password: cGFzc3dvcmQ= # base64 encoded value of 'password'
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /etc/secret
          name: secret-volume
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret
