apiVersion: v1
kind: Service
metadata:
  name: cluster-monitoring-service
spec:
  selector:
    app: cluster-monitoring
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
