apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: stress-test
  template:
    metadata:
      labels:
        app: stress-test
    spec:
      containers:
        - name: stress
          image: vish/stress
          resources:
            requests:
              cpu: "1000m"
          args:
            - -cpus
            - "1"
